[project]
name = "uipath-langgraph-agent"
version = "1.1.1"
description = "uipath-langgraph-agent"
authors = [{ name = "James Dickson", email = "james.dickson@uipath.com" }]
dependencies = [
    "uipath-langchain>=0.0.140",
    "langchain-anthropic>=0.3.8",
]
requires-python = ">=3.10"
