[project]
name = "uipath-chat-agent"
version = "1.0.0"
description = "uipath-chat-agent"
authors = [{ name = "James Dickson", email = "james.dickson@uipath.com" }]
dependencies = [
    "uipath-langchain>=0.0.106",
    "langchain-anthropic>=0.3.8",
]
requires-python = ">=3.10"
